### ISSUE TITLE
Drop space before slash in empty elements

### ISSUE THREAD

**Issue by infotexture** [prettier/plugin-xml#11]
Currently, the plug-in enforces a space before the closing slash in empty elements when `xmlSelfClosingTags` is `true`, normalizing `<foo></foo>` and `<foo/>` to `<foo />`.

Some projects prefer the tighter `<foo/>` syntax, so if an option already exists to configure empty tag handling, perhaps a third value could be added to support this convention, like:

- `true` (no space) – `<foo/>`
- `false` – `<foo></foo>`
- `space` (current behavior) – `<foo />`

If so, this setting could also be applied to the [XML declaration](https://www.w3.org/TR/xml/#NT-XMLDecl), to permit 

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

instead of rewriting to insert an extra space before the closing `?>` as noted in #3:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
```

**Comment by kddeisz** [comment]
This is now on master as `xmlSelfClosingSpace`

**Comment by infotexture** [comment]
@kddeisz 🙏 Thanks for the initial implementation in b415dcfc8191eda6d26afe998a5aac54f729e374 for 0.5.0.

The new option seems to work fine when added to the Prettier configuration file, for example as:

```yaml
# .prettierrc.yaml

# https://github.com/prettier/plugin-xml/issues/11
xmlSelfClosingSpace: false
```

— but I get a warning when passing the new option via the CLI:

```shell
$ prettier --write "index.dita" --parser=xml --xmlSelfClosingSpace false
[warn] Ignored unknown option --xmlSelfClosingSpace=false.
index.dita 21ms
```

**Comment by kddeisz** [comment]
@infotexture yeah on the command line it's `--xml-self-closing-space`.

**Comment by infotexture** [comment]
@kddeisz Ah, right, easy to forget that. See #48 ☝️ for a proposal.

**Comment by infotexture** [comment]
@kddnewton The changelog says the `xmlSelfClosingSpace` option that fixed this issue was [removed](https://github.com/prettier/plugin-xml/blob/main/CHANGELOG.md#removed) from the 1.0.0 release.

Does that mean all instances of `<foo/>` will revert to `<foo />`, or is there some other way to preserve the tighter spaceless syntax in self-closing elements and XML declarations?

**Comment by kddnewton** [comment]
@infotexture Yeah that option was dropped after feedback from the community when I opened the PR to merge this plugin into prettier core.

**Comment by gtwohig** [comment]
@kddnewton too bad that it was dropped as lack of this feature is a blocker for us going to 1.0.

Use case: we are cleaning up/standardizing formatting on XML that is returned to us via the Salesforce metadata API. They (salesforce) do not include a space before the `?>` on the xml version line nor do they on self closing elements. With xmlSelfClosingSpace: false the only files with a diff after the pull are ones that have a substantive change. This allows pretty-quick to run super fast because only a few files need to be prettified.  With the 1.0 behavior we have thousands of files with whitespace only diffs that need to be cleaned up by prettier eliminating the significant speed improvements we get from pretty-quick.

**Comment by infotexture** [comment]
I also have client projects that are sticking with the previous version for this reason. 😞

**Comment by kddnewton** [comment]
Ehh alright. You convinced me. I'll release that today.

**Comment by infotexture** [comment]
Much appreciated. 
Thank you. 🙏

**Comment by gtwohig** [comment]
Thanks @kddnewton excited to be on the latest version and everything seems to be working great!
