### ISSUE TITLE
Wrong whitespace added to csproj

### ISSUE THREAD

**Issue by viceice** [prettier/plugin-xml#113]
editorconfig:
*  `max_line_length = 120`

current:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ProjectTypeGuids>
      {C1CDDADD-2546-481F-9697-4EA41081F2FC};{14822709-B5A1-4724-98CA-57A101D1B079};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
    </ProjectTypeGuids>
</Project>
```

expected
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ProjectTypeGuids
        >{C1CDDADD-2546-481F-9697-4EA41081F2FC};{14822709-B5A1-4724-98CA-57A101D1B079};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
</Project>
```

msbuild tooling has problems with the added whitespaces. 😢 Current workaround is to extend  `max_line_length = 160`

**Comment by viceice** [comment]
also this doesn't work because `VSToolsPath` now has whitespaces.

```xml
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">
      $(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)
    </VSToolsPath>
  </PropertyGroup>
  <Import
    Project="$(VSToolsPath)\SharePointTools\Microsoft.VisualStudio.SharePoint.targets"
    Condition="'$(VSToolsPath)' != ''"
```

**Comment by kddeisz** [comment]
In your configuration do you have it so that it's ignoring whitespace?

**Comment by viceice** [comment]
Yes, otherwise it wouldn't align xml elements

**Comment by kddeisz** [comment]
So that's the problem. In XML every tag is by default whitespace-sensitive unless the schema otherwise specifies, which is why by default we do our best to preserve whitespace under `whitespaceSensitivity=strict`. If you switch it to `ignore`, it's going to ignore whitespace sensitivity entirely. What it seems like you want in this case is some elements to have whitespace sensitivity and some not, which we don't currently support.

The best advice I can offer you is to keep it so that it's ignoring whitespace sensitivity, but then to wrap anything that you explicitly need it to respect whitespace with a prettier ignore comment, as in:

```xml
<PropertyGroup>
  <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
  <!-- prettier-ignore-start -->
  <VSToolsPath Condition="'$(VSToolsPath)' == '>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  <!-- prettier-ignore-end -->
</PropertyGroup>
```
