### ISSUE TITLE
Output is bad formated  V0.10.0+

### ISSUE THREAD

**Issue by celm1990** [prettier/plugin-xml#172]
**Original data**
![image](https://user-images.githubusercontent.com/7775116/111852548-5206d580-88e5-11eb-82ce-9e8ea8f7f5ae.png)

**Before V0.10.0**

![image](https://user-images.githubusercontent.com/7775116/111852572-74005800-88e5-11eb-987b-aefbca517c2d.png)

**After V0.10.0+**
![image](https://user-images.githubusercontent.com/7775116/111852600-91cdbd00-88e5-11eb-95de-0c21f350aa97.png)

**.prettierrc**
![image](https://user-images.githubusercontent.com/7775116/111852817-6bf4e800-88e6-11eb-87b6-b43a8b051cd3.png)

I hope not duplicate of https://github.com/prettier/plugin-xml/issues/169

**Comment by kddeisz** [comment]
What would you expect the output to be?

**Comment by celm1990** [comment]
As image **before V0.10.0** Not new lines, blank spaces is wrong, I used Qweb for compile this output, but new lines has not compile source correctly

**Comment by viceice** [comment]
Struggling with this too 😕

**Comment by kddnewton** [comment]
Okay, so the issue here is that you're passing `xmlWhitespaceSensitivity` as `"ignore"`, but clearly you have whitespace-sensitive markup.

There are two ways you can fix this. Either you can pass `xmlWhitespaceSensitivity` as `"strict"` or you use ignore ranges like we describe in the README (https://github.com/prettier/plugin-xml#ignore-ranges).

**Comment by kddnewton** [comment]
Actually drastically increasing the `printWidth` should do it as well.

**Comment by celm1990** [comment]
Thank so much, change at` xmlWhitespaceSensitivity: "strict"` working fine
