### ISSUE TITLE
XML Parser

### ISSUE THREAD

**Issue by bd82** [prettier/plugin-xml#18]
Hello.

I see this package uses a heavily modified fork of the [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser).

I am assuming(?) the fork was done to deal with syntactic constructs which may not be represented in the output of common XML Parser (e.g Comments).

I have recently released [@xml-tools/parser](https://github.com/SAP/xml-tools/tree/master/packages/parser) which produces a Concrete Syntax Tree(CST).

This means that the **whole** "parse tree" is available in the output (e.g comments, processing instructions, CDATA sections,...). This parser is implemented using the [Chevrotain Parser Building Library](https://github.com/SAP/chevrotain) which is also used in the [prettier-java plugin](https://github.com/jhipster/prettier-java).

**Perhaps @xml-tools/parser could be useful for the implementation of prettier-plugin-xml?**

## Possible Pros
- Extract Parsing concerns/maintenance from this repo.
- Perhaps the AST Won't even be needed as the CST can be printed directly
  - See [prettier-plugin-toml](https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml/lib)

## Possible Cons
- @xml-tools/parser is young, so expect some bugs...
- losing direct control of the dependency (basically fork vs consume question).

## Other Points to consider
- Performance numbers (I have not benchmarked, but I doubt this would be a concern
  as the actual printing of the new text in prettier seems to be the bottleneck and Chevrotain based Parsers are [pretty fast](https://sap.github.io/chevrotain/performance/)).
- larger package size (including deps), but I doubt this is a big concern for a CLI tool.

**Thoughts?**

**Comment by kddeisz** [comment]
Interesting! Yeah the fork was done to handle a bunch of stuff it didn’t previously handle. I’d be very interested in checking out the newer project, currently on vacation for another week but I’ll check it out when I get back.

**Comment by bd82** [comment]
Here is a little prototype that builds (some of) the current AST with `@xml-tools/parser
- https://github.com/prettier/plugin-xml/pull/20

Although as described in the PR, I would not personally recommend using this approach.

**Comment by rart** [comment]
There are use cases for prettier on the web/browser (hence prettier standalone). Please do consider bundle size and other aspects related to web/browser usage.

**Comment by bd82** [comment]
> There are use cases for prettier on the web/browser (it’s not exclusively a CLI tool, hence prettier standalone). Please do consider bundle size and other aspects related to web/browser usage.

The Chevrotain minified is 158KB. This may not be optimal for browser usage
but it is also not a blocker.

Prettier standalone itself seems to have multiple files > 1mb.
- https://unpkg.com/browse/prettier@1.19.1/

**Comment by bd82** [comment]
Hi @kddeisz 

I understands you are currently very busy.
I can help push this topic forward by working on an XML printer that works on a CST output of a Chevrotain based Parser.
- Would look similar to this [TOML printer](https://github.com/bd82/toml-tools/blob/master/packages/prettier-plugin-toml/lib/printer.js)
- I already did some work on this (In XMl Context) in the past, so it is more about aligning to the existing tests expected output than re-writing from scratch.

However I'd like to understand if this is aligned with this project's goals/design
before investing my time in it as it would virtually be project re-write.
- Yeah its a small project but still...

Cheers.
Shahar.

**Comment by marceloschreiber** [comment]
Hi @kddeisz and @bd82,

joining the party to say that I ended up doing this (still in very early stages) before reading this issue. My motivations were:
1. When working with UI5 projects (SAP's frontend framework) this plugin has a bug as described at https://github.com/prettier/plugin-xml/issues/23.
2. To my understanding, UI5 projects will probably want to have some specific rules that might conflict with what is expected for a standard XML formatting. E.g: I like to have each attribute on its own line when working with UI5 projects. This led me to play around on how I could format a view to be exactly how I wanted.
3. I knew nothing about AST, tokens, etc and developing it seemed like a fun way to pass the time.

Then I analyzed the existing parsers, found the [prettier-java plugin](https://github.com/jhipster/prettier-java) which led me to [@xml-tools/parser](https://github.com/SAP/xml-tools/tree/master/packages/parser). With only the **print** part missing I decided to see what could be done.

[prettier-plugin-ui5view](https://github.com/marceloschreiber/prettier-plugin-ui5view) is the end result. In the test folder, you can see what I mean by formatting in a different way than standard XML. 

I don't intend to maintain it as npm package, because I want to reach out to the UI5 core team and ask if they're interested in having an official SAP's plugin just for the UI5 views.


Regards!

**Comment by bd82** [comment]
> I decided to see what could be done.

👍 

> UI5 projects will probably want to have some specific rules that might conflict with what is expected for a standard XML formatting. E.g: I like to have each attribute on its own line when working with UI5 projects.

Could this option not be part of an existing formatter? Is a separate project really needed?

**Comment by marceloschreiber** [comment]
> Could this option not be part of an existing formatter? Is a separate project really needed?

I rather enhance this plugin than create a different project.

Although UI5 has a unique characteristic where some XML attributes have a JSON on its value. Since prettier allows adding another formatter on top of a formatter, I think it would be best to format both the XML and the JSON attributes. This might be something too specific to add to this plugin.

**Comment by kddeisz** [comment]
Thanks everyone! I've updated the plugin to use `@xml-tools/parser` and it's much more stable. You can see the work in https://github.com/prettier/plugin-xml/pull/39. It's about to be merged so I'm going to close this.
